import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="w-full border-b border-b-slate-300 p-2 flex flex-row place-content-evenly items-center">
          <Link href={'/'}>
            <h1 className="text-3xl antialiased">Usuários & Postagens</h1>
          </Link>
          <Link href={"/login"}>
            <span className="bg-slate-300 rounded-md p-2">Log in</span>
          </Link>
        </header>
        {children}
      </body>
    </html>
  );
}
